# Version 1.2.0
<#
.SYNOPSIS
    STEP 1b (optional) — Creates dummy VMs in vCenter and tags them in NSX,
    so that NSX DFW tag-based groups are populated before real VMs are migrated.

.DESCRIPTION
    Reads the NSX_VMTags.csv produced by Export-NSX-DFW.ps1 and:
      1. Collects every unique scope:tag combination across the entire CSV.
         NSX enforces a hard limit of 30 tags per VM, so the unique tags are
         split into chunks of 30 and one dummy VM is created per chunk:
           NSX-DUMMY-01   <- unique tags 1-30
           NSX-DUMMY-02   <- unique tags 31-60
           NSX-DUMMY-03   <- unique tags 61-90  (etc.)
         The number of dummy VMs required is ceil(uniqueTags / 30), regardless
         of how many source VMs exist. A tag used by 500 VMs still only needs
         to appear once, on one dummy VM.

      2. Creates that many tiny powered-off VMs in vCenter (cloned from a
         template or built from scratch) and records each vCenter UUID.
      3. Waits until NSX fabric discovery picks up each new VM (polls
         /api/v1/fabric/virtual-machines by external_id).
      4. Applies the tag chunk to each dummy VM using the same
         /api/v1/fabric/virtual-machines?action=update_tags endpoint that
         Import-NSX-DFW.ps1 uses.

    After the real VMs are migrated and their tags are set, run
    Import-NSX-DFW.ps1 -ImportTags $true to tag the real VMs, then delete
    the dummy VMs from vCenter.

    REQUIREMENTS
    ─────────────────────────────────────────────────────────────
    • PowerShell 5.1+ or PowerShell 7+ on Windows
    • VMware PowerCLI module  (Install-Module VMware.PowerCLI)
    • Network access to both vCenter and NSX Manager
    • A vCenter datastore, cluster/host, and folder to place the dummy VMs
    • A vCenter "dummy template" VM to clone from  — OR use -SkipVCenter to skip
      VM creation entirely (if dummy VMs are created by another process)

    ALTERNATIVE: -SkipVCenter
    ─────────────────────────────────────────────────────────────
    If you already have a way to create VMs in vCenter and just want this script
    to wait for NSX fabric discovery and apply the tags, pass -SkipVCenter $true
    together with -ExternalIdMap pointing to a CSV with columns VMDisplayName and
    ExternalId.  The script will skip VM creation and jump straight to tagging.

.PARAMETER NSXManager
    FQDN or IP of the destination NSX Manager.

.PARAMETER VCenter
    FQDN or IP of the vCenter that manages the destination NSX environment.
    Not required when -SkipVCenter $true.

.PARAMETER TagsCsv
    Path to NSX_VMTags.csv produced by Export-NSX-DFW.ps1.

.PARAMETER Datacenter
    vCenter datacenter name where dummy VMs will be created.

.PARAMETER Cluster
    vCenter cluster (or standalone host) name to place the dummy VMs on.

.PARAMETER Datastore
    vCenter datastore name for the dummy VM configuration files.

.PARAMETER VMFolder
    vCenter VM folder path for dummy VMs (e.g. "Discovered virtual machine"
    or a custom folder like "NSX-Dummy"). Created if it doesn't exist.
    Default: "NSX-Dummy-VMs"

.PARAMETER TemplateVM
    Name of an existing vCenter VM or template to clone for each dummy VM.
    The clone is created as a thin-provisioned, powered-off VM.
    If omitted, the script creates a minimal VM from scratch (no disks,
    1 vCPU, 4 MB RAM, BIOS firmware) — sufficient for NSX tag assignment.

.PARAMETER DummyVMPrefix
    String prepended to each dummy VM name to avoid name clashes.
    Default: "NSX-DUMMY-"

.PARAMETER SkipVCenter
    Skip VM creation in vCenter entirely. Requires -ExternalIdMap.
    Default: $false

.PARAMETER ExternalIdMap
    Path to a CSV with columns DummyVMName and ExternalId, used when
    -SkipVCenter $true. One row per dummy VM. Maps each dummy VM name to its
    vCenter UUID so that NSX tags can be applied directly.
    This file is auto-generated by a previous run of this script.

.PARAMETER FabricPollIntervalSec
    Seconds between NSX fabric polling attempts per VM.
    Default: 15

.PARAMETER FabricPollTimeoutSec
    Maximum seconds to wait for a VM to appear in NSX fabric inventory.
    Default: 300

.PARAMETER LogFile
    Path to a log file. Required when -LogTarget is 'File' or 'Both'.

.PARAMETER LogTarget
    Controls where log output is written.
      Screen : colored output to the console only (default)
      File   : write to -LogFile only, no console output
      Both   : colored console output AND written to -LogFile

.EXAMPLE
    # Full flow: create dummy VMs and tag them
    .\Seed-NSX-DFW-DummyVMs.ps1 `
        -NSXManager nsx9.corp.local `
        -VCenter    vc.corp.local   `
        -TagsCsv    .\NSX_VMTags.csv `
        -Datacenter "DC01" `
        -Cluster    "Cluster01" `
        -Datastore  "vsanDatastore"

.EXAMPLE
    # Skip VM creation — dummy VMs already exist; just apply tags
    .\Seed-NSX-DFW-DummyVMs.ps1 `
        -NSXManager   nsx9.corp.local `
        -TagsCsv      .\NSX_VMTags.csv `
        -SkipVCenter  $true `
        -ExternalIdMap .\DummyVM_ExternalIds.csv

.NOTES
    Cleanup: after real VM migration, delete dummy VMs from vCenter and
    re-run Import-NSX-DFW.ps1 -ImportTags $true to tag the real VMs.
#>

[CmdletBinding(SupportsShouldProcess)]
param(
    [Parameter(Mandatory)][string]$NSXManager,
    [string]$VCenter            = '',
    [Parameter(Mandatory)][string]$TagsCsv,
    [string]$Datacenter         = '',
    [string]$Cluster            = '',
    [string]$Datastore          = '',
    [string]$VMFolder           = 'NSX-Dummy-VMs',
    [string]$TemplateVM         = '',
    [string]$DummyVMPrefix      = 'NSX-DUMMY-',
    [bool]$SkipVCenter          = $false,
    [string]$ExternalIdMap      = '',
    [int]$FabricPollIntervalSec = 15,
    [int]$FabricPollTimeoutSec  = 300,
    [string]$LogFile            = '',
    [ValidateSet('Screen','File','Both')]
    [string]$LogTarget          = 'Screen'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ─────────────────────────────────────────────────────────────
# LOGGING
# ─────────────────────────────────────────────────────────────
function Write-Log {
    param(
        [string]$Message,
        [ValidateSet('INFO','WARN','ERROR','SUCCESS')][string]$Level = 'INFO'
    )
    $ts   = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    $line = "[$ts][$Level] $Message"
    $color = switch ($Level) {
        'WARN'    { 'Yellow' }
        'ERROR'   { 'Red'    }
        'SUCCESS' { 'Green'  }
        default   { 'Cyan'   }
    }
    if ($LogTarget -eq 'Screen' -or $LogTarget -eq 'Both') {
        Write-Host $line -ForegroundColor $color
    }
    if (($LogTarget -eq 'File' -or $LogTarget -eq 'Both') -and $LogFile) {
        try   { Add-Content -Path $LogFile -Value $line -Encoding UTF8 }
        catch { Write-Host "[WARN] Could not write to log file: $_" -ForegroundColor Yellow
                Write-Host $line -ForegroundColor $color }
    }
}

# ─────────────────────────────────────────────────────────────
# IGNORE SELF-SIGNED CERTIFICATES (NSX REST)
# ─────────────────────────────────────────────────────────────
if (-not ([System.Management.Automation.PSTypeName]'TrustAllCerts').Type) {
    Add-Type @"
using System.Net;
using System.Security.Cryptography.X509Certificates;
public class TrustAllCerts : ICertificatePolicy {
    public bool CheckValidationResult(ServicePoint sp, X509Certificate cert,
        WebRequest req, int problem) { return true; }
}
"@
}
[System.Net.ServicePointManager]::CertificatePolicy = New-Object TrustAllCerts
[System.Net.ServicePointManager]::SecurityProtocol  = [System.Net.SecurityProtocolType]::Tls12

# ─────────────────────────────────────────────────────────────
# VALIDATE PARAMETERS
# ─────────────────────────────────────────────────────────────
if (-not $SkipVCenter) {
    foreach ($p in @('VCenter','Datacenter','Cluster','Datastore')) {
        if (-not (Get-Variable $p -ValueOnly)) {
            Write-Log "-$p is required when -SkipVCenter is `$false." ERROR
            exit 1
        }
    }
} else {
    if (-not $ExternalIdMap) {
        Write-Log "-ExternalIdMap is required when -SkipVCenter is `$true." ERROR
        exit 1
    }
    if (-not (Test-Path $ExternalIdMap)) {
        Write-Log "ExternalIdMap file not found: $ExternalIdMap" ERROR
        exit 1
    }
}

if (-not (Test-Path $TagsCsv)) {
    Write-Log "TagsCsv file not found: $TagsCsv" ERROR
    exit 1
}

# ─────────────────────────────────────────────────────────────
# NSX CREDENTIALS & HEADERS
# ─────────────────────────────────────────────────────────────
Write-Log "Enter credentials for NSX Manager: $NSXManager"
$NsxCred  = Get-Credential -Message "NSX ($NSXManager) credentials"
$pair     = "$($NsxCred.UserName):$($NsxCred.GetNetworkCredential().Password)"
$bytes    = [System.Text.Encoding]::ASCII.GetBytes($pair)
$NsxHeaders = @{
    Authorization  = "Basic $([Convert]::ToBase64String($bytes))"
    'Content-Type' = 'application/json'
}

# ─────────────────────────────────────────────────────────────
# NSX REST HELPERS
# ─────────────────────────────────────────────────────────────
function Invoke-NsxGet {
    param([string]$Path)
    $uri = "https://$NSXManager$Path"
    try   { return Invoke-RestMethod -Uri $uri -Method GET -Headers $NsxHeaders }
    catch { Write-Log "GET $uri failed: $_" ERROR; return $null }
}

function Invoke-NsxPost {
    param([string]$Path, [string]$JsonBody)
    $uri = "https://$NSXManager$Path"
    try {
        Invoke-RestMethod -Uri $uri -Method POST -Headers $NsxHeaders -Body $JsonBody | Out-Null
        return $true
    } catch {
        $detail = if ($_.ErrorDetails -and $_.ErrorDetails.Message) { " | Detail: $($_.ErrorDetails.Message)" } else { '' }
        Write-Log "POST $uri failed: $_$detail" ERROR
        return $false
    }
}

# ─────────────────────────────────────────────────────────────
# LOAD TAGS CSV
# ─────────────────────────────────────────────────────────────
Write-Log "Loading VM tags from: $TagsCsv" INFO
$tagRows = Import-Csv -Path $TagsCsv -Encoding UTF8
Write-Log "  Loaded $(@($tagRows).Count) tag row(s)." INFO

# ── Collect every unique scope:tag pair across the whole CSV ─
# Order is preserved (first-seen) so output is deterministic.
$seenKeys   = [System.Collections.Generic.HashSet[string]]::new()
$uniqueTags = [System.Collections.Generic.List[hashtable]]::new()

foreach ($row in $tagRows) {
    $key = "$($row.TagScope)`0$($row.TagValue)"   # null-byte separator avoids false collisions
    if ($seenKeys.Add($key)) {
        $uniqueTags.Add(@{ scope = $row.TagScope; tag = $row.TagValue })
    }
}
Write-Log "  Unique scope:tag combinations: $($uniqueTags.Count)" INFO

# ── Split unique tags into chunks of $MaxTagsPerVM ───────────
# One dummy VM is created per chunk, named NSX-DUMMY-01, -02, …
$MaxTagsPerVM = 30
$totalChunks  = [math]::Ceiling($uniqueTags.Count / $MaxTagsPerVM)
Write-Log "  Dummy VMs required: $totalChunks (max $MaxTagsPerVM tags each)" INFO

# $vmChunks — flat list of @{ DummyVMName='...'; Tags=@(...) }
$vmChunks = [System.Collections.Generic.List[hashtable]]::new()

for ($i = 0; $i -lt $totalChunks; $i++) {
    $chunk     = $uniqueTags | Select-Object -Skip ($i * $MaxTagsPerVM) -First $MaxTagsPerVM
    $dummyName = '{0}{1:D2}' -f $DummyVMPrefix, ($i + 1)   # NSX-DUMMY-01, NSX-DUMMY-02, …
    $vmChunks.Add(@{
        DummyVMName = $dummyName
        Tags        = @($chunk)
    })
}

# ─────────────────────────────────────────────────────────────
# STATISTICS
# ─────────────────────────────────────────────────────────────
$Stats = @{ VMsCreated=0; VMsFound=0; VMsTagged=0; TagErrors=0; Skipped=0; Errors=0 }

# ═════════════════════════════════════════════════════════════
# PHASE 1 — CREATE DUMMY VMs IN vCENTER
# ═════════════════════════════════════════════════════════════

# Maps DummyVMName → ExternalId (UUID) — populated in Phase 1
$externalIdByDummy = @{}

if ($SkipVCenter) {
    # ── Load pre-built external ID map ───────────────────────
    Write-Log "━━━ SkipVCenter: loading external ID map ━━━" INFO
    $mapRows = Import-Csv -Path $ExternalIdMap -Encoding UTF8
    foreach ($r in $mapRows) {
        $externalIdByDummy[$r.DummyVMName] = $r.ExternalId
    }
    Write-Log "  Loaded $($externalIdByDummy.Count) mapping(s) from ExternalIdMap." INFO
} else {
    # ── Create dummy VMs via PowerCLI ────────────────────────
    Write-Log "━━━ Connecting to vCenter: $VCenter ━━━" INFO

    # Check PowerCLI availability
    if (-not (Get-Module -ListAvailable -Name 'VMware.VimAutomation.Core')) {
        Write-Log "VMware PowerCLI is not installed. Install it with: Install-Module VMware.PowerCLI" ERROR
        exit 1
    }
    Import-Module VMware.VimAutomation.Core -ErrorAction Stop

    # Suppress PowerCLI CEIP / deprecation messages
    Set-PowerCLIConfiguration -Scope User -ParticipateInCeip $false -Confirm:$false | Out-Null
    Set-PowerCLIConfiguration -InvalidCertificateAction Ignore -Confirm:$false | Out-Null

    $VcCred = Get-Credential -Message "vCenter ($VCenter) credentials"
    Connect-VIServer -Server $VCenter -Credential $VcCred -ErrorAction Stop | Out-Null
    Write-Log "  Connected to vCenter $VCenter." SUCCESS

    # Resolve vCenter objects
    $dc         = Get-Datacenter -Name $Datacenter -ErrorAction Stop
    $clusterObj = Get-Cluster    -Name $Cluster    -Location $dc -ErrorAction Stop
    $dsObj      = Get-Datastore  -Name $Datastore  -ErrorAction Stop

    # Resolve (or create) the VM folder
    $folderObj = Get-Folder -Name $VMFolder -Type VM -Location $dc -ErrorAction SilentlyContinue
    if (-not $folderObj) {
        Write-Log "  VM folder '$VMFolder' not found — creating it." WARN
        $folderObj = New-Folder -Name $VMFolder -Location (Get-Folder -Name 'vm' -Type VM -Location $dc) -ErrorAction Stop
        Write-Log "  Created VM folder: $VMFolder" SUCCESS
    }

    # Resolve optional template
    $templateObj = $null
    if ($TemplateVM) {
        $templateObj = Get-VM       -Name $TemplateVM -ErrorAction SilentlyContinue
        if (-not $templateObj) { $templateObj = Get-Template -Name $TemplateVM -ErrorAction SilentlyContinue }
        if (-not $templateObj) { Write-Log "TemplateVM '$TemplateVM' not found. Falling back to scratch VM creation." WARN }
    }

    Write-Log "━━━ Creating dummy VMs ($($vmChunks.Count) total) ━━━" INFO

    foreach ($chunk in $vmChunks) {
        $dummyName = $chunk.DummyVMName

        # Check if dummy VM already exists
        $existing = Get-VM -Name $dummyName -ErrorAction SilentlyContinue
        if ($existing) {
            Write-Log "  SKIP: '$dummyName' already exists in vCenter (UUID: $($existing.ExtensionData.Config.Uuid))." WARN
            $externalIdByDummy[$dummyName] = $existing.ExtensionData.Config.Uuid
            $Stats.Skipped++
            continue
        }

        if (-not $PSCmdlet.ShouldProcess($dummyName, 'Create dummy VM in vCenter')) { continue }

        try {
            if ($templateObj) {
                # Clone from template / VM
                $cloneSpec            = New-Object VMware.Vim.VirtualMachineCloneSpec
                $cloneSpec.PowerOn    = $false
                $cloneSpec.Template   = $false
                $relocSpec            = New-Object VMware.Vim.VirtualMachineRelocateSpec
                $relocSpec.Datastore  = $dsObj.ExtensionData.MoRef
                $relocSpec.Pool       = $clusterObj.ExtensionData.ResourcePool
                $cloneSpec.Location   = $relocSpec

                $task    = $templateObj.ExtensionData.CloneVM_Task($folderObj.ExtensionData.MoRef, $dummyName, $cloneSpec)
                $taskObj = Get-Task -Id "Task-$($task.Value)" -ErrorAction SilentlyContinue
                if ($taskObj) { Wait-Task -Task $taskObj | Out-Null }
                $newVM   = Get-VM -Name $dummyName -ErrorAction Stop
            } else {
                # Create a minimal VM from scratch (no disks, no OS)
                $newVM = New-VM `
                    -Name         $dummyName `
                    -ResourcePool $clusterObj `
                    -Datastore    $dsObj `
                    -Location     $folderObj `
                    -NumCpu       1 `
                    -MemoryMB     4 `
                    -GuestId      'otherGuest64' `
                    -ErrorAction  Stop
            }

            $uuid = $newVM.ExtensionData.Config.Uuid
            $externalIdByDummy[$dummyName] = $uuid
            $Stats.VMsCreated++
            Write-Log "  ✔ Created '$dummyName'  UUID: $uuid  ($($chunk.Tags.Count) tags)" SUCCESS

        } catch {
            Write-Log "  ✗ Failed to create '$dummyName': $_" ERROR
            $Stats.Errors++
        }
    }

    # Export external ID map so it can be consumed by -SkipVCenter on a future re-run.
    $mapCsvPath = Join-Path (Split-Path $TagsCsv) 'DummyVM_ExternalIds.csv'
    $vmChunks |
        Where-Object { $externalIdByDummy.ContainsKey($_.DummyVMName) } |
        ForEach-Object {
            [PSCustomObject]@{
                DummyVMName = $_.DummyVMName
                ExternalId  = $externalIdByDummy[$_.DummyVMName]
            }
        } |
        Export-Csv -Path $mapCsvPath -NoTypeInformation -Encoding UTF8
    Write-Log "  External ID map saved to: $mapCsvPath" INFO

    Disconnect-VIServer -Server $VCenter -Confirm:$false
    Write-Log "  Disconnected from vCenter." INFO
}

# ═════════════════════════════════════════════════════════════
# PHASE 2 — WAIT FOR NSX FABRIC DISCOVERY
# ═════════════════════════════════════════════════════════════
Write-Log "━━━ Verifying NSX Manager connectivity ━━━" INFO
$nodeInfo = Invoke-NsxGet -Path "/api/v1/node"
if ($nodeInfo) { Write-Log "  Connected: NSX $($nodeInfo.product_version)" SUCCESS }
else           { Write-Log "Cannot connect to NSX Manager $NSXManager." ERROR; exit 1 }

Write-Log "━━━ Waiting for dummy VMs to appear in NSX fabric inventory ━━━" INFO

# $confirmedChunks — chunks whose dummy VM was confirmed in NSX fabric
$confirmedChunks = [System.Collections.Generic.List[hashtable]]::new()

foreach ($chunk in $vmChunks) {
    $dummyName = $chunk.DummyVMName

    if (-not $externalIdByDummy.ContainsKey($dummyName)) {
        Write-Log "  SKIP: no ExternalId recorded for '$dummyName' (creation may have failed)." WARN
        $Stats.Skipped++
        continue
    }

    $eid     = $externalIdByDummy[$dummyName]
    $elapsed = 0
    $found   = $false

    Write-Log "  Polling NSX fabric for '$dummyName' (UUID: $eid)..." INFO

    while ($elapsed -lt $FabricPollTimeoutSec) {
        $resp = Invoke-NsxGet -Path "/api/v1/fabric/virtual-machines?external_id=$eid&included_fields=display_name,external_id"
        if ($resp -and $resp.result_count -gt 0) {
            $found = $true
            $confirmedChunks.Add(@{
                DummyVMName = $dummyName
                ExternalId  = $eid
                Tags        = $chunk.Tags
            })
            $Stats.VMsFound++
            Write-Log "  ✔ '$dummyName' found in NSX fabric (elapsed: ${elapsed}s)." SUCCESS
            break
        }
        Start-Sleep -Seconds $FabricPollIntervalSec
        $elapsed += $FabricPollIntervalSec
    }

    if (-not $found) {
        Write-Log ("  ✗ Timeout: '$dummyName' (UUID: $eid) did not appear in NSX fabric " +
                   "within ${FabricPollTimeoutSec}s. Skipping tag assignment.") WARN
        $Stats.Skipped++
    }
}

# ═════════════════════════════════════════════════════════════
# PHASE 3 — APPLY TAGS IN NSX
# ═════════════════════════════════════════════════════════════
Write-Log "━━━ Applying NSX tags to dummy VMs ━━━" INFO

foreach ($confirmed in $confirmedChunks) {
    $dummyName = $confirmed.DummyVMName
    $eid       = $confirmed.ExternalId
    $tags      = $confirmed.Tags

    if (-not $tags -or $tags.Count -eq 0) {
        Write-Log "  SKIP: '$dummyName' has no tags to apply." WARN
        $Stats.Skipped++
        continue
    }

    # Defensive guard — should never exceed 30 after chunking, but belt-and-braces
    if ($tags.Count -gt $MaxTagsPerVM) {
        Write-Log ("  ERROR: '$dummyName' chunk contains $($tags.Count) tags, " +
                   "exceeding the $MaxTagsPerVM limit. Skipping to avoid API rejection.") ERROR
        $Stats.TagErrors++
        continue
    }

    $body = @{ external_id = $eid; tags = @($tags) } | ConvertTo-Json -Depth 5 -Compress

    if ($PSCmdlet.ShouldProcess($dummyName, "Apply $($tags.Count) NSX tag(s)")) {
        $ok = Invoke-NsxPost -Path "/api/v1/fabric/virtual-machines?action=update_tags" -JsonBody $body
        if ($ok) {
            $Stats.VMsTagged++
            $tagSummary = ($tags | ForEach-Object { "$($_.scope):$($_.tag)" }) -join ', '
            Write-Log "  ✔ Tagged '$dummyName' ($($tags.Count) tags): $tagSummary" SUCCESS
        } else {
            $Stats.TagErrors++
        }
    }
}

# ═════════════════════════════════════════════════════════════
# SUMMARY
# ═════════════════════════════════════════════════════════════
Write-Log "════════════════════════════════════════════" INFO
Write-Log " SEED SUMMARY" INFO
Write-Log "────────────────────────────────────────────" INFO
Write-Log "  Unique tags found         : $($uniqueTags.Count)"   INFO
Write-Log "  Dummy VMs created         : $($Stats.VMsCreated)"   INFO
Write-Log "  Dummy VMs found in fabric : $($Stats.VMsFound)"     INFO
Write-Log "  Dummy VMs tagged          : $($Stats.VMsTagged)"    INFO
Write-Log "  Tag errors                : $($Stats.TagErrors)"    $(if ($Stats.TagErrors -gt 0) { 'ERROR' } else { 'INFO' })
Write-Log "  Skipped                   : $($Stats.Skipped)"      WARN
Write-Log "  Errors                    : $($Stats.Errors)"       $(if ($Stats.Errors -gt 0) { 'ERROR' } else { 'INFO' })
Write-Log "────────────────────────────────────────────" INFO
Write-Log " NEXT STEPS" INFO
Write-Log "  1. Run Import-NSX-DFW.ps1 to import DFW objects (groups, policies)." INFO
Write-Log "     Tag-based groups will already resolve against the dummy VMs." INFO
Write-Log "  2. Migrate your real VMs to the destination environment." INFO
Write-Log "  3. Re-apply tags to real VMs using Import-NSX-DFW.ps1 -ImportTags `$true." INFO
Write-Log "  4. Delete the '$DummyVMPrefix*' dummy VMs from vCenter." INFO
Write-Log "════════════════════════════════════════════" INFO